### ISSUE TITLE
Can't get it to work. 

### ISSUE THREAD

**Issue by kevinSuttle** [pekastel/hyperterm-initial-windows#1]
My config: https://gist.github.com/kevinSuttle/2f680f9fbaf2fd324551910bb5c0345a#file-hyperterm-js-L53

**Comment by ChristinWhite** [comment]
Same here. I'll look into the code and see if I can figure out what's going on.

**Comment by pekastel** [comment]
Hi @kevinSuttle, I was looking at your gist and didn't see the option "initialWindows".  That's the number of windows to open on init so maybe that's why it's failing.

Here's an example of my current configuration:

```
    initialWindows: '3',                                                                   

    initialWindowsPosition: [                                                              
      {x: 0, y: 0, width: 800, height: 500},                                               
      {x: 0, y: 550, width: 900, height: 400},                                             
      {x: 850, y: 0, width: 700, height: 500}                                              
    ],                                                                                     

```

@christopherdwhite are you still having problems?

P.S.:
Sorry for the delay!

**Comment by kevinSuttle** [comment]
Thanks @pekastel. Unfortunately, it doesn't matter what kind of config I pass it.

``` js
initialWindows: 1,
initialWindowsPosition: {
          x: 800,
          y: 0,
          width: 1200,
          height: 900
      },
```

``` js
  initialWindows: '2', // the quotes don't matter either way
  initialWindowsPosition:[{
      x: 800,
      y: 0,
      width: 1200,
      height: 900
    },
    {
        x: 100,
        y: 20,
        width: 800,
         height: 400
      }],
```

Is there maybe something with HyperTerm that is misconfigured? Like it's pulling the config from the wrong place?

**Comment by kevinSuttle** [comment]
Ok, so here's what I had to do to get it working.
1. Make sure the plugin is listed as the first one.
2. Make sure the `initialWindows` and coords are under `config`.
3. There is a conflict with `hyperterm-tabs`.  A separate issue.
   - If you have it listed in your plugins, you get 1 window and 2 tabs.  

I've updated my config to reflect.
